New third Q for muni bndys
agrc/gis.utah.gov pull request #1503
Opened 2020-09-24 21:05 UTC by mheagin

new blog for the third quarter update for municipal boundaries.

2020-09-28 23:28 UTC, atribolet commented
Hey! Wasn't able to get to this today, but I'll try to take a look at it tomorrow morning, fyi!

2020-10-05 16:43 UTC, atribolet requested changes

2020-10-05 16:43 UTC, atribolet commented on _posts/2020-09-24-municipal-boundaries-update-for-third-quarter-2020-calendar-year
> +title: 'Municipal Boundaries update for Third Quarter 2020 (calendar year)'
```suggestion
title: 'Municipal Boundaries Update for Third Quarter 2020 (Calendar Year)'
```

2020-10-05 16:43 UTC, atribolet commented on _posts/2020-09-24-municipal-boundaries-update-for-third-quarter-2020-calendar-year
> +  - Utah Municipalities
```suggestion
  - utah municipalities
```

2020-10-05 16:43 UTC, atribolet commented on _posts/2020-09-24-municipal-boundaries-update-for-third-quarter-2020-calendar-year
> +  - Municipal Boundary
```suggestion
  - municipal boundary
```

2020-10-05 16:43 UTC, atribolet commented on _posts/2020-09-24-municipal-boundaries-update-for-third-quarter-2020-calendar-year
> +  - Municipalities
```suggestion
  - municipalities
```

2020-10-05 16:43 UTC, atribolet commented on _posts/2020-09-24-municipal-boundaries-update-for-third-quarter-2020-calendar-year
> +  - Boundaries
```suggestion
  - boundaries
```

2020-10-05 16:43 UTC, atribolet commented on _posts/2020-09-24-municipal-boundaries-update-for-third-quarter-2020-calendar-year
> +  - Annexations
```suggestion
  - annexations
```

2020-10-05 16:43 UTC, atribolet commented on _posts/2020-09-24-municipal-boundaries-update-for-third-quarter-2020-calendar-year
> +Following are the changes and annexations since July 2020, listed by County and City:
```suggestion
The following table shows the changes and annexations (listed by county and city) since July 2020:
```

2020-10-05 16:43 UTC, atribolet commented on _posts/2020-09-24-municipal-boundaries-update-for-third-quarter-2020-calendar-year
> +We are into the third quarter now, almost through the year. While things have slowed down some life goes on. Annexations have been coming through as cities grow and for this year we have two possible
```suggestion
As we move into the third quarter of 2020, the year is almost through. While some things have slowed down, life goes on. Annexations have been coming through as cities grow, and for this year we have two possible new incorporations: one in Tooele County (Erda) and another in Weber County (West Weber). Both new incorporations will be on the ballots in the coming election. 
```

2020-10-05 16:43 UTC, atribolet commented on _posts/2020-09-24-municipal-boundaries-update-for-third-quarter-2020-calendar-year
> +Here are the updates for the third quarter.
```suggestion
```

2020-10-05 16:43 UTC, atribolet commented on _posts/2020-09-24-municipal-boundaries-update-for-third-quarter-2020-calendar-year
> +As always these changes to town and city boundaries can affect other departments too, be sure to share your data with others.
```suggestion
As always, changes to town and city boundaries can affect other data layers, so if you are involved in municipal and county data, be sure to share your data with others. 
```

2020-10-05 16:43 UTC, atribolet commented on _posts/2020-09-24-municipal-boundaries-update-for-third-quarter-2020-calendar-year
> +Municipalities and updates can be viewed here: Utah Municipality Modifications
```suggestion
Municipality updates can be viewed on the ArcGIS Utah Municipality Modifications page.
```

2020-10-05 16:43 UTC, atribolet commented
K, @steveoh I made some slight changes to this. Feel free to take a look and implement the edits as you see fit. Let me know if you have any questions!

2020-10-05 17:11 UTC, steveoh approved these changes

2020-10-05 17:12 UTC, merged