Telecom boundary Porter update
agrc/gis.utah.gov pull request #2435
Opened 2024-01-08 19:20 UTC by ZachBeck

2024-01-08 19:32 UTC, steveoh requested changes
- [ ] The url should change from `telephone-infrastructure-and-rural-telcom-boundaries` to something more reflective of this new dataset. e.g. `telecom-boundaries`. 
- [ ] the stewardship sheet needs to reflect this url so the sgid index works
- [ ] an entry in `_redirects` should be created for the old and new url so we don't break the internet
- [ ] This utility index page should have the title, description, and link updated
   <img width="1162" alt="image" src="https://github.com/agrc/gis.utah.gov/assets/325813/b9de5338-3564-4b56-b4d0-451ba911fc7a">
- [ ] The thumbnail is probably misleading
   <img width="286" alt="image" src="https://github.com/agrc/gis.utah.gov/assets/325813/fd9eb596-bc9f-48cf-bcf4-291cb8503e93">

2024-01-09 00:11 UTC, ZachBeck commented
What's misleading about the thumbnail, all of those providers are still in the data? It is ugly though...

2024-01-09 02:21 UTC, steveoh commented
> What's misleading about the thumbnail, all of those providers are still in the data? It is ugly though...

I assumed it was "probably misleading" since it was created with only the rural telecom boundaries? I'm fine without creating a new one. I wanted to bring it up though. It's not that time consuming to create a new thumbnail either.

2024-01-16 23:12 UTC, steveoh approved these changes

2024-01-16 23:12 UTC, merged